# Generated by Django 3.0.3 on 2020-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
