# Generated by Django 3.0.3 on 2020-03-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
    ]
