# Generated by Django 3.0.3 on 2020-03-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
