# Generated by Django 3.0.3 on 2020-03-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200323_0345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
