# Generated by Django 2.2.4 on 2020-12-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
