# Generated by Django 3.0.3 on 2020-03-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200318_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='password',
        ),
    ]
