# Generated by Django 3.0.3 on 2020-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
